config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root 'emissions#index' # Set the root path to the index action
  resources :emissions, only: [:new, :create, :show, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/emission.rb
class Emission < ApplicationRecord
  MAX_FILE_ROW_COUNT = 100_000

  has_one_attached :file
  has_many :emission_calculations

  validate :validate_row_count, on: :create

  private

  def validate_row_count
    return unless file.attached?

    file_handler = FileHandler.new(attachment_changes['file'].attachable)

    if file_handler.row_count > MAX_FILE_ROW_COUNT
      errors.add(:file, "contains more than #{MAX_FILE_ROW_COUNT} rows")
    end
  end
end

app/models/emission_calculation.rb
class EmissionCalculation < ApplicationRecord
  belongs_to :emission
  belongs_to :emission_factor
end

app/models/emission_factor.rb
class EmissionFactor < ApplicationRecord
  validates_uniqueness_of :uuid
  has_many :emission_calculations

  def self.normalize(str)
    str.parameterize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/emissions_controller.rb
class EmissionsController < ApplicationController
  def index
    @emissions = Emission.all
  end

  def new
    @emission = Emission.new
  end

  def create
    @emission = Emission.new(emission_params)
    if @emission.save
      ProcessEmissionJob.perform_later(@emission.id)
      redirect_to @emission
    else
      render :new
    end
  end

  def show
    @emission = Emission.find(params[:id])
    @emission_calculations = @emission.emission_calculations
  end

  private

  def emission_params
    params.require(:emission).permit(:file, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/emissions/index.html.erb
<h1 class="text-2xl font-bold mb-4">Emissions</h1>

<table class="min-w-full divide-y divide-gray-200">
  <thead class="bg-gray-50">
    <tr>
      <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Name</th>
      <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">File Name</th>
      <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Uploaded At</th>
      <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Actions</th>
    </tr>
  </thead>
  <tbody class="bg-white divide-y divide-gray-200">
    <% @emissions.each do |emission| %>
      <tr>
        <td class="px-6 py-4 whitespace-nowrap"><%= emission.name %></td>
        <td class="px-6 py-4 whitespace-nowrap"><%= emission.file.filename %></td>
        <td class="px-6 py-4 whitespace-nowrap"><%= emission.created_at.strftime("%B %d, %Y %H:%M") %></td>
        <td class="px-6 py-4 whitespace-nowrap">
          <%= link_to 'Show', emission_path(emission), class: "text-indigo-600 hover:text-indigo-900" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Upload New Emission File', new_emission_path, class: "mt-4 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700" %>

app/views/emissions/new.html.erb
<div class="w-1/2 md:w-1/3 m-auto">
  <h1 class="block text-2xl font-bold">Upload Emission</h1>
  <%= form_with model: @emission, local: true, class: "space-y-4" do |form| %>
    <div>
      <%= form.label :name, class: "block text-sm font-medium text-gray-700" %>
      <%= form.text_field :name, class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm sm:text-sm" %>
    </div>
    <div>
      <%= form.label :file, class: "block text-sm font-medium text-gray-700" %>
      <%= form.file_field :file, class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm sm:text-sm" %>
    </div>
    <div>
      <%= form.submit "Upload", class: "inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700" %>
    </div>
  <% end %>
</div>

app/views/emissions/show.html.erb
<h1 class="text-2xl font-bold mb-4"><%= "Emission Calculations For #{@emission.name}"%></h1>

<table class="min-w-full divide-y divide-gray-200">
  <thead class="bg-gray-50">
    <tr>
      <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Quantity</th>
      <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Emission Factor Name</th>
      <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">CO2 Emission (g)</th>
      <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Source</th>
    </tr>
  </thead>
  <tbody class="bg-white divide-y divide-gray-200">
    <% @emission_calculations.each do |calc| %>
      <tr>
        <td class="px-6 py-4 whitespace-nowrap"><%= calc.quantity %></td>
        <td class="px-6 py-4 whitespace-nowrap"><%= calc.emission_factor.name %></td>
        <td class="px-6 py-4 whitespace-nowrap"><%= calc.value %></td>
        <td class="px-6 py-4 whitespace-nowrap"><%= calc.source %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Co2EmissionCalculator</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <main class="mt-28 px-5">
      <%= yield %>
    </main>
  </body>
</html>